### ISSUE TITLE
Blur/Touched event from select-field

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-select-field#10]
I need an event to let me know when the select field has been touched. Other things like datepicker or general inputs, I can use the `blur` event, but there isn't an equivalent option on the sky-select-field.

Ideally we could just have an output eventEmitter `blur` or another name to surface this event (when onTouched is called).

Current workaround involves using `@ViewChild(SkySelectFieldComponent)` and re-registering the onTouched callback to one I control (which cancels out angular forms module's callback). I'd prefer not to keep using this workaround.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.0`
