### ISSUE TITLE
Select Field Doesn't Handle Long Labels Well

### ISSUE THREAD

**Issue by Blackbaud-DanielHiggins** [blackbaud/skyux-select-field#13]
### Expected behavior
When using the Sky Select field and the selected item has a label that is longer than the textbox, the label overflows.

![image](https://user-images.githubusercontent.com/17032145/49465860-8fa2cb80-f7cc-11e8-8d57-6a4114c7b1af.png)

### Actual behavior
When the label is too long for the select field, the label should be truncated.

### Steps to reproduce
1. Add sky-select-field to a page
2. Add an option whose label length is longer than can be displayed in the sky-select-field element.
3. Set selected value for sky-select-field to option from step 2.

### Plunker
https://plnkr.co/edit/Br9WZN6D46h7PKeKtLHo?p=preview

### Impact
This prevents our usage of this control.  When the text exceeds the field, it looks pretty bad.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.1.0`
