### ISSUE TITLE
Additional picker views for select field

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-select-field#14]
@Blackbaud-ToddRoberts commented on [Wed Jul 26 2017](https://github.com/blackbaud/skyux2/issues/941)

The current list-style layout for list-view-checklist is too restrictive for some scenarios. There should be an option for a repeater-style checklist layout that allows for custom content layouts in the row.

**Comment by Blackbaud-ToddRoberts** [comment]
duplicate #41
