### ISSUE TITLE
Remove pagination from Select Field Component

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux-select-field#15]
@Blackbaud-AlexKingman commented on [Wed Aug 15 2018](https://github.com/blackbaud/skyux2/issues/1912)

Pagination has led to some confusion on the intent and usage of the Select Field Component, so we need to strip it out.

From @Blackbaud-ToddRoberts:
> We should remove paging from Select Field - the use case for the component is a browsable list, if a list is so long that it's unmanageable to scroll, the Lookup component would be more appropriate as the user is most likely going to be searching anyway.

Once removing pagination, the component should scroll vertically, just like it does in SKY UX 1: https://skyux.developer.blackbaud.com/components/selectfield/

**Comment by Blackbaud-ToddRoberts** [comment]
Feedback from users is that pagination is causing confusion about which items are selected in the case of multiselect mode with multiple pages.

**Comment by Blackbaud-AlexKingman** [comment]
Investigate using infinite scroll.
