### ISSUE TITLE
Option to search against a remote source

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux-select-field#16]
### Expected behavior
In the search box in a select field, the search can optionally be done on a remote source.

### Actual behavior
The search is only done on the loaded data.

**Comment by Blackbaud-ToddRoberts** [comment]
Dashboard builder uses Select Field to define filters, and the option sets for some of them can get too large to load up front. Users need to be able to search a remote source for cases where what they are looking isn't otherwise loaded.

**Comment by Blackbaud-DiHuynh** [comment]
The Online Donation Forms team has a need for building an input for RE NXT Appeals. Clients might have a lot of appeals, and some clients might not know what they are looking for. Ideally, clients can browse through a list of appeals and also search for what they want

**Comment by Blackbaud-LouisPujol** [comment]
Would it also not be easier to allow the user to hook up a dataProvider as opposed to just preloaded data? Then the search can execute against the provider just like the sky-list component does

**Comment by Blackbaud-AlexKingman** [comment]
A solution has been introduced in `3.5.0`. See the [changelog](https://github.com/blackbaud/skyux-select-field/blob/3.5.0/CHANGELOG.md) for more information. Docs change will be coming next. You can watch that progress here: https://github.com/blackbaud/skyux2-docs/issues/865
