### ISSUE TITLE
Support error handling 

### ISSUE THREAD

**Issue by Blackbaud-DiHuynh** [blackbaud/skyux-select-field#36]
### Expected behavior
When the user clicks on the select field, the SPA makes a backend call, if that back end call fails, user sees a sky-error in the modal.

### Actual behavior
They see an empty select modal

### Severity
medium - high

### Impact
any teams using a select-field with a backend call will need this error handling

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-DiHuynh The `data` input accepts an observable stream. Is it possible to catch any errors from the backend before opening the select field?

**Comment by Blackbaud-DiHuynh** [comment]
The use case we have is for an optional field. For a required field, we show the sky-error on the parent component of the select-field. We didn't want to error out the whole form because of an error on an optional field

**Comment by Blackbaud-AlexKingman** [comment]
As @Blackbaud-SteveBrush says above, the recommended approach here is to tap into the `data` input stream. Closing.
