### ISSUE TITLE
IE11 > Opening select field displays text vertically

### ISSUE THREAD

**Issue by Blackbaud-ScottFreeman** [blackbaud/skyux-select-field#37]
### Expected behavior
Opening a select field on supported browsers should look similar.

### Actual behavior
IE11 is pretty much unusable.  Text is displayed vertically.

### Steps to reproduce
Got to demo page here in IE11
https://developer.blackbaud.com/skyux/components/select-field
Open a select field

### Severity
High for IE11 users

### Impact
Makes it difficult to select items.  Clicking around causes things to display appropriately.

**Comment by Blackbaud-TrevorBurch** [comment]
This also affects the column picker on list view grids. I have bumped up the impact based on this.

**Comment by Blackbaud-ScottFreeman** [comment]
What is necessary to trigger a release for a fix?  This issue was closed 10 days ago but there hasn't been a release in 21 days.

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ScottFreeman Sorry for the confusion. The issue shouldn't have been closed until the release was done. I'll work on getting the release out.

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-ScottFreeman actually I lied. This was fixed via a fix in the `modals` library. That should have been called out here when we closed the issue. Sorry for the confusion!

https://github.com/blackbaud/skyux-modals/blob/master/CHANGELOG.md

Fixed in `@skyux/modals` version `3.1.0`
