### ISSUE TITLE
Allow for custom template in modal

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-select-field#41]
There are a few teams that need the ability to use a repeater or tree view in the select field modal. Instead of baking these templates into the select field, we should allow for custom templates AND a custom data model.

Related: https://github.com/blackbaud/skyux-select-field/issues/20

**Comment by Blackbaud-ToddRoberts** [comment]
Approved
https://blackbaudinc.box.com/s/gqaqk7cjppz4kqo25lfx2nec9kw2lotn

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.4.0`
