### ISSUE TITLE
If only one select item and configured to do so don't show field but label of the one item

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [blackbaud/skyux-select-field#77]
### Expected behavior

If select field is configured to do so and only has one select item don't show the field but the label of the one item.

https://blackbaud.slack.com/archives/C3TQ4C0KG/p1596121851046700?thread_ts=1595868326.426900&cid=C3TQ4C0KG

**Comment by Blackbaud-JasonBodnar** [comment]
#76

**Comment by Blackbaud-SteveBrush** [comment]
Needs more info: How would the "readonly" pattern be applied to all SKY UX components/fields? This is something we need to research before applying it as a one-off to select-field.
