### ISSUE TITLE
Should Show Wait Indicator While Data Loads

### ISSUE THREAD

**Issue by Blackbaud-VanesaiXiong** [blackbaud/skyux-select-field#93]
### Expected behavior
Show a wait indicator while waiting for time consuming Observables to emit data.

### Actual behavior
There is currently no wait indicator.

### Steps to reproduce
[stackblitz demo](https://stackblitz.com/edit/angular-9anjgy?file=src/app/select-field-demo.component.ts)

### Severity
Low

### Impact
Low

**Comment by Blackbaud-DanMiller** [comment]
not fixing at this time as we are working on a new select field pattern
